name: Test PHP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Test
      run: | 
        php -v
        
    - name: Use Github 
      run: |
        git --version
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git status

       
     
        
