name: VN Develop CakePHP Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: CakePHP sniffer
      run: | 
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
        php composer-setup.php --1 
        php -r "unlink('composer-setup.php');"
        php composer.phar require cakephp/cakephp-codesniffer
        curl -o /diff.txt --request GET 'https://api.github.com/repos/marketenterprise/oikura/pulls/2114?state=all' --header 'Accept: application/vnd.github.v3.diff' --header 'Authorization: token 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' --header 'User-Agent: GitAction' > /dev/null 2>&1
        export diff_files=($(cat /diff.txt | grep -Eo 'diff.\-\-git.a\/([a-zA-Z\_\-\/\.]+\.php)' | grep -Eo 'oikura_api.*$'))
        for diff_file in "${diff_files[@]}"; do echo $diff_file; done

    - name: run test
      run: | 
        echo $diff_file

       
     
        
