name: VN Develop CakePHP Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check PHP --version
      run: php --version  
      
    - name: Install composer for cakephp dir 
      run: | 
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
        php composer-setup.php --1 
        php -r "unlink('composer-setup.php');"
        php composer.phar --version
        
    - name: Install cakephp codesniffer package
      run: | 
        php composer.phar require global cakephp/cakephp-codesniffer
      
    
       
     
        
